### ISSUE TITLE
The output is still incomplete

### ISSUE THREAD

**Issue by iworldtong** [zengxianyu/co-mod-gan-pytorch#2]
python test.py -i imgs/ffhq_in.png -m imgs/ffhq_m.png -o ./imgs/example_output.jpg -c checkpoints/co-mod-gan-ffhq-9-025000.pth
doesn't work

**Comment by zengxianyu** [comment]
what input image and mask?

**Comment by iworldtong** [comment]
ffhq_in.png ffhq_m.png
python test.py -i imgs/ffhq_in.png -m imgs/ffhq_m.png -o ./imgs/ffhq_o.png -c checkpoints/co-mod-gan-ffhq-9-025000.pth
and [result_img](https://sm.ms/image/2bmzcuQnqvIpY3t)

**Comment by zengxianyu** [comment]
I got reasonable results by running this command 

<a href="https://imgtu.com/i/RJaMDJ"><img src="https://z3.ax1x.com/2021/06/27/RJaMDJ.png" alt="RJaMDJ.png" border="0" /></a>

Maybe your pth file is corrupted in downloading. Could you download and try again?

**Comment by iworldtong** [comment]
(I changed it to "parser.add_argument('--device', help='cpu|cuda', default='cuda:1')")
The result is correct, when using "parser.add_argument('--device', help='cpu|cuda', default='cuda:0')"
