### ISSUE TITLE
Conversion from TF Version to PyTorch

### ISSUE THREAD

**Issue by codeislife99** [zengxianyu/co-mod-gan-pytorch#5]
Hi, 
     Do you mind elaborating on how you converted the TF Version to PT ? Did you convert using onnx or some other model converter and then wrote the PT code or did you train the PT code from scratch and created your own weights ? On the first glance it seems you did the former ?

**Comment by zengxianyu** [comment]
I did this manually. The weights are from the tf version

**Comment by codeislife99** [comment]
Okay thanks
